feat: add ZkEVMBridgeExecutor
sparkdotfi/spark-gov-relay pull request #10
Opened 2023-10-29 12:16 UTC by 0xdapper

Pulled and little changed from https://github.com/aave/governance-crosschain-bridges/pull/78

2023-11-01 12:45 UTC, hexonaut requested changes
Need some changes, and there is a critical security issue.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +interface IZkEvmBridgeLike {
This interface is unused. It can be removed.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +interface IBridgeMessageReceiver {
Let's match the name in `xchain-helpers`: `IZkEvmBridgeMessageReceiver`.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +    address public immutable ZKEVM_BRIDGE;
This is unused causing compiler error.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +    error UnauthorizedBridgeCaller();
This error is unused.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +    uint32 internal constant _MAINNET_NETWORK_ID = 0;
Let's make this immutable and set by the constructor.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +contract ZkEVMBridgeExecutor is L2BridgeExecutor, IBridgeMessageReceiver {
Instead of inheriting from `L2BridgeExecutor` and setting the `onlyEthereumGovernanceExecutor` modifier to revert, I would just inherit from `BridgeExecutorBase` in the same way `GnosisBridgeExecutor` does.

2023-11-01 12:45 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +    function onMessageReceived(address originAddress, uint32 originNetwork, bytes calldata data) external payable {
Missing `msg.sender` check being the `zkEVMBridge`. This can be called by anyone.

2023-11-06 17:43 UTC, hexonaut requested changes
Looking better, but still need some changes.

2023-11-06 17:43 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
>      error NotDirectlyCallable();
This error is unused.

2023-11-06 17:43 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
>      address internal immutable zkEVMBridge;
This should be `public`.

2023-11-06 17:43 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +    uint32 internal immutable _MAINNET_NETWORK_ID;
This should be `public` and called `originNetworkId`.

2023-11-06 17:43 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +    address internal _ethereumGovernanceExecutor;
The underscore could be removed, this made `public` and the getting function removed.

2023-11-06 17:43 UTC, hexonaut commented on src/executors/ZkEVMBridgeExecutor.sol
> +        uint32 mainnetNetworkId
I would make this more general and have `_originNetworkId` or similar.

2023-11-10 13:27 UTC, hexonaut approved these changes, later dismissed
Good to merge after Polygon has internal reviewer/auditor.

2023-11-17 10:40 UTC, barrutko requested changes
`test/ZkEVMBridgeExecutor.t.sol` should be renamed to `test/ZkEVMCrosschainTest.t.sol`.

Other than that LGTM.

2023-11-20 14:03 UTC, hexonaut approved these changes

2024-03-26 06:59 UTC, merged