General bringing repo up to date
sparkdotfi/spark-gov-relay pull request #12
Opened 2024-03-26 07:06 UTC by hexonaut

Latest forge-std, xchain-helpers and fixing the CI. Removed some unused imports too.

2024-03-26 19:06 UTC, lucas-manuel approved these changes

2024-03-26 19:07 UTC, lucas-manuel requested changes
CI failing

2024-03-28 05:38 UTC, hexonaut commented
Disabled zkEVM for now.

2024-03-28 14:42 UTC, lucas-manuel approved these changes

2024-03-29 02:15 UTC, merged