[SC-430] Revert on non-existent contract instead of silent success
sparkdotfi/spark-gov-relay pull request #17
Opened 2024-06-08 07:27 UTC by hexonaut

Switched to using the OZ `Address` helper library which does an additional check for empty addresses and reverts if so. This will help with things like cross-chain payload e2e testing to have them fail when the address is not deployed. Also added some more testing coverage for these types of failure cases with delegatecall and call.

2024-06-10 11:40 UTC, barrutko approved these changes, later dismissed

2024-06-10 12:57 UTC, lucas-manuel requested changes

2024-06-10 12:57 UTC, lucas-manuel commented on test/AuthBridgeExecutor.t.sol
> +        // Trigger some evm error like trying to call a non-payable function
Can remove comment

2024-06-10 12:57 UTC, lucas-manuel commented on test/AuthBridgeExecutor.t.sol
> +        // Trigger some evm error like trying to call a non-payable function
Remove comment

2024-06-11 07:28 UTC, hexonaut commented on test/AuthBridgeExecutor.t.sol
> +        // Trigger some evm error like trying to call a non-payable function
fixed

2024-06-11 07:28 UTC, hexonaut commented on test/AuthBridgeExecutor.t.sol
> +        // Trigger some evm error like trying to call a non-payable function
fixed

2024-06-11 09:37 UTC, barrutko approved these changes

2024-06-11 13:20 UTC, lucas-manuel approved these changes

2024-06-11 13:20 UTC, merged