[SC-160] Add contribution guidelines
sparkdotfi/spark-gov-relay pull request #4
Opened 2023-09-26 12:19 UTC by barrutko

2023-09-27 01:16 UTC, hexonaut requested changes
Some small changes.

2023-09-27 01:16 UTC, hexonaut commented on README.md
> +3. If they are any dependencies required, copy them into `/src/dependencies/<YOUR_DOMAIN_NAME>` directory.
`they` -> `there` in second word

2023-09-27 01:16 UTC, hexonaut commented on README.md
> +6. Get an approving review from at least two of three designated reviewers - @hexonaut, @lucas-manuel and @barrutko
We prefer the teams to mostly review their own work, but I would say they need at least 1 review from us (2 total).

2023-09-27 04:58 UTC, hexonaut approved these changes, later dismissed
LGTM

2023-10-03 02:37 UTC, lucas-manuel submitted a review, later dismissed
LGTM

2023-10-03 04:05 UTC, hexonaut approved these changes

2023-10-03 09:19 UTC, lucas-manuel approved these changes

2023-10-03 09:43 UTC, merged