[SC-150] Add Gnosis Chain
sparkdotfi/spark-gov-relay pull request #5
Opened 2023-09-27 02:51 UTC by barrutko

- [ ] Add bridge executor
- [ ] Add crosschain forwarder
- [ ] Add test suite for the new domain
- [ ] Test functions specific to the newly added contracts
(Actually we I'm not sure if we need the AMB, ChainID and Controller reconfiguration - we can consider deleting these)

CURRENTLY BLOCKED. Waiting for XChain Helpers.

2023-10-06 03:59 UTC, hexonaut approved these changes, later dismissed
LGTM

2023-10-06 10:04 UTC, lucas-manuel requested changes
Code LGTM, lets just add a test for the forwarder to ensure that the call to the AMB is being performed as expected using vm.expectCall

2023-10-06 10:04 UTC, lucas-manuel commented on test/GnosisCrosschainTest.t.sol
> +import { CrosschainTestBase } from './CrosschainTestBase.sol';
```suggestion
import 'forge-std/Test.sol';

import { Domain, GnosisDomain } from 'xchain-helpers/GnosisDomain.sol';

import { IAMB, GnosisBridgeExecutor } from 'src/executors/GnosisBridgeExecutor.sol';
import { CrosschainForwarderGnosis }  from 'src/forwarders/CrosschainForwarderGnosis.sol';
import { IL2BridgeExecutor }          from 'src/interfaces/IL2BridgeExecutor.sol';

import { IBaseCrosschainForwarder } from './interfaces/IBaseCrosschainForwarder.sol';
import { IExecutor }                from './interfaces/IExecutor.sol';

import { GnosisReconfigurationPayload } from './mocks/GnosisReconfigurationPayload.sol';

import { CrosschainTestBase } from './CrosschainTestBase.sol';
```

2023-10-06 10:04 UTC, lucas-manuel commented on test/GnosisCrosschainTest.t.sol
> +        bridgedDomain = new GnosisDomain(getChain('gnosis_chain'), hostDomain);
```suggestion
        hostDomain    = new Domain(getChain('mainnet'));
        bridgedDomain = new GnosisDomain(getChain('gnosis_chain'), hostDomain);
```

2023-10-06 10:04 UTC, lucas-manuel commented on src/executors/GnosisBridgeExecutor.sol
> +contract GnosisBridgeExecutor is BridgeExecutorBase {
Confirmed only change between this file and https://github.com/gnosis/governance-crosschain-bridges/blob/master/contracts/bridges/AMBBridgeExecutor.sol is the name of the contract `AMBBridgeExecutor => GnosisBridgeExecutor`

2023-10-06 10:04 UTC, lucas-manuel commented on src/forwarders/CrosschainForwarderGnosis.sol
> +import {IL2BridgeExecutor} from '../interfaces/IL2BridgeExecutor.sol';
Confirmed change is just from importing from our own dir

2023-10-06 10:04 UTC, lucas-manuel commented on src/forwarders/CrosschainForwarderGnosis.sol
> +contract CrosschainForwarderGnosis {
Confirmed change is in contract name `CrosschainForwarderAMB => CrosschainForwarderGnosis`

2023-10-06 10:04 UTC, lucas-manuel commented on src/forwarders/CrosschainForwarderGnosis.sol
> +  }
Confirmed that diff is that we set our own execurot on init. This is necessary because we will need our own bridge executor (admin for spark L2)

2023-10-08 17:54 UTC, lucas-manuel approved these changes

2023-10-09 08:41 UTC, hexonaut approved these changes

2023-10-09 08:46 UTC, merged