Refactor formatting
sparkdotfi/spark-gov-relay pull request #8
Opened 2023-10-17 08:40 UTC by barrutko

2023-10-17 14:39 UTC, hexonaut submitted a review, later dismissed
LGTM

2023-10-23 16:00 UTC, lucas-manuel requested changes
Since we're doing it can we update all imports that are doing `{this}` to do `{ this }` as well?

2023-10-23 16:00 UTC, lucas-manuel commented on test/CrosschainTestBase.sol
> +        );
These can be left as is imo, looks better

2023-10-23 16:00 UTC, lucas-manuel commented on test/GnosisCrosschainTest.t.sol
>  contract GnosisCrosschainTest is CrosschainTestBase {
Leave new line

2023-10-23 16:00 UTC, lucas-manuel commented on test/GnosisCrosschainTest.t.sol
>      }
Leave new line

2023-10-24 08:48 UTC, barrutko commented on test/CrosschainTestBase.sol
> +        );
Frankly, I prefer the multiline formatting for asserts, as it's more visually clear what two values are being compared.
If you have a super strong opinion here though, I can change it back to single line.

2023-10-24 17:00 UTC, lucas-manuel approved these changes

2023-10-24 17:06 UTC, hexonaut approved these changes
LGTM

2023-10-25 09:51 UTC, merged